name: reviewdog
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Catch repo code
        uses: actions/checkout@v3
      - name: Check code
        run:  ls -al
      - name: Setup golang env
        uses: actions/setup-go@v3
      - name: Check golang env
        run:  go env
      - name: Run code
        run:  go run main.go
      - name: Install golangci-lint And Check
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Check golangci-lint linters
        run: golangci-lint linters
      - name: Test golangci-lint
        run: golangci-lint run

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
#      - name: Run pull-request reviewdog
#        env:
#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        if:
#
#      - name: Run push reviewdog